import AuthProvider from "./AuthProvider";
import "./globals.css";
import NavMenu from "./NavMenu";
import { Open_Sans } from "next/font/google";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = Open_Sans({ weight: "400", subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className={myFont.className}>
          <NavMenu />
          <div className={styles.container}>{children}</div>
        </body>
      </html>
    </AuthProvider>
  );
}
